name: Docker Client Images CI
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # outputs only supports text, number and boolean values
      modified_files: ${{ steps.matrix.outputs.modified_files }}
      is_list_empty: ${{ steps.matrix.outputs.is_list_empty_conditional}}
    steps:
      - id: matrix
        run: |
          # bash has arrays like (1 2 3) but we need a json parseable output
          # we need to work with strings instead
          modified_files=(1,2)
          for i in {3..10}; do
              # if we start with an empty string idk how to handle the comma at the start
              modified_files+=(,${i})
          done
          echo modified_files=\[${modified_files[@]}\] >> $GITHUB_OUTPUT
          # ^this line prints "modified_files=[1,2,3,4,5]" then gh parses it and sets outputs.modified_files = "[1,2,3,4,5]"
          # which then we parse in the matrix.value part
          
  build:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        value: ${{ fromJson(needs.setup.outputs.modified_files) }}
    steps:
      - id: print_vars
        run: |
          echo ${{needs.setup.outputs.modified_files}}          
          echo ${{matrix}}
