name: Docker Client Images CI
on:
  push:
    branches: [ “main” ]
  pull_request:
    branches: [ “main” ]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.matrix.outputs.list_modified_files }}
      is_list_empty: ${{ steps.matrix.outputs.is_list_empty_conditional}}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: matrix
        run: |
          declare -a modified_files=(‘test’, ‘test’)
          is_list_empty=‘true’
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo “File: ${changed_file}”
            if [[ ${changed_file} == *“Dockerfile” ]]; then
              modified_files+=(“${changed_file}“)
              echo “Modified: ${changed_file}”
            fi
          done
          if [[ $(( ${#modified_files[@]} )) < 1 ]]; then
            is_list_empty=‘false’
          fi
          echo list_modified_files=${modified_files[@]} >> $GITHUB_OUTPUT
          echo is_list_empty_conditional=${is_list_empty} >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{needs.setup.outputs.is_list_empty}}
    strategy:
      matrix:
        value: [""]
    steps:
      - id: print_list
        run: |
          echo ${{needs.setup.outputs.modified_files}}
          echo ${{matrix}}
#           for file in ${{ needs.setup.outputs.modified_files }}; do
#             echo ${file}
#           done
