name: Docker Client Images CI
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      modified_files: ${{ steps.matrix.outputs.list_modified_files }}
      is_list_empty: ${{ steps.matrix.outputs.is_list_empty_conditional}}
    steps:
      - id: matrix
        run: |
          declare -a modified_files=(‘test’, ‘test’)
          is_list_empty=‘true’
          for i in {1 .. 10}; do
            echo “File: ${i}”
          done
          echo modified_files=${modified_files[@]} >> $GITHUB_OUTPUT
          echo is_list_empty=${is_list_empty} >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{needs.setup.outputs.is_list_empty}}
    strategy:
      matrix:
        value: [""]
    steps:
      - id: print_list
        run: |
          echo ${{needs.setup.outputs.modified_files}}
          echo ${{needs.setup.outputs.is_list_empty}}
          echo ${{matrix}}
#           for file in ${{ needs.setup.outputs.modified_files }}; do
#             echo ${file}
#           done
